import React from 'react'
import AuditLogCard from './AuditLogCard';
import ReportHistoryCard from './ReportHistoryCard';
const ReportHistoryAuditlog = () => {
    const auditLogs = [
        { generatedBy: 'Reporte Accessed', dateTime: 'Sarah jones' },
        { generatedBy: 'Report Download', dateTime: 'Sarah jones Admin ' },
    ];
     const reportlogs = [
        { generatedBy: 'Generated by Sarah Johnson', dateTime: 'July 1, 2023 - 09:00 AM' },
        { generatedBy: 'Generated by John Smith', dateTime: 'July 2, 2023 - 10:30 AM' },
    ];
    return (
        <>
            <div className='row d-flex align-items-stretch mt-3 '>
                <div className='col-md-6 d-flex'>
                    <div className='card flex-fill'>
                        <div className='card-body'>
                            <h2 className='heading-blue-20'>
                                Report History
                            </h2>
                            {reportlogs.map((log, index) => (

                                <ReportHistoryCard generatedBy={log.generatedBy} dateTime={log.dateTime} />

                            ))}
                        </div>
                    </div>
                </div>
                <div className='col-md-6 d-flex'>
                    <div className='card flex-fill'>
                        <div className='card-body'>
                            <h2 className='heading-blue-20'>
                                Audit Log
                            </h2>
                            {auditLogs.map((log, index) => (

                                <AuditLogCard generatedBy={log.generatedBy} dateTime={log.dateTime} />

                            ))}
                        </div>
                    </div>
                </div>
            </div>

        </>
    )
}

export default ReportHistoryAuditlog
